# Generated by Django 3.2.8 on 2021-10-29 07:17

import accounts.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default_profile_img.jpeg', upload_to=accounts.models.profile_image_path),
        ),
    ]
