# Generated by Django 3.2.8 on 2021-11-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
