# Generated by Django 3.2.8 on 2021-10-28 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ninkname',
            new_name='nickname',
        ),
    ]
