# Generated by Django 3.2.8 on 2021-10-28 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reader',
            new_name='producer',
        ),
    ]
