# Generated by Django 3.2.8 on 2021-11-05 06:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_alter_comment_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='StoryComment',
        ),
        migrations.RenameModel(
            old_name='Img',
            new_name='StoryImg',
        ),
    ]
